### ISSUE TITLE
Icon ETL in CI cannot write to the last_synced_block.txt file

### ISSUE THREAD

**Issue by pranav925** [geometry-labs/icon-blocks#107]
```
Error: l_1             | 2021-10-30 01:50:38,743 - root [ERROR] - An exception occurred while syncing block data.
etl_1             | Traceback (most recent call last):
etl_1             |   File "/icon-etl/iconetl/streaming/instrumented_streamer.py", line 120, in _do_stream
etl_1             |     synced_blocks = self._sync_cycle()
etl_1             |   File "/icon-etl/iconetl/streaming/instrumented_streamer.py", line 157, in _sync_cycle
etl_1             |     write_last_synced_block(self.last_synced_block_file, target_block)
etl_1             |   File "/icon-etl/iconetl/streaming/instrumented_streamer.py", line 184, in write_last_synced_block
etl_1             |     write_to_file(file, str(last_synced_block) + "\n")
etl_1             |   File "/icon-etl/iconetl/streaming/instrumented_streamer.py", line 204, in write_to_file
etl_1             |     with smart_open(file, "w") as file_handle:
etl_1             |   File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
etl_1             |     return next(self.gen)
etl_1             |   File "/usr/local/lib/python3.6/site-packages/blockchain_etl_common-1.6.1-py3.6.egg/blockchainetl_common/file_utils.py", line 33, in smart_open
etl_1             |     fh = get_file_handle(filename, mode, binary, create_parent_dirs)
etl_1             |   File "/usr/local/lib/python3.6/site-packages/blockchain_etl_common-1.6.1-py3.6.egg/blockchainetl_common/file_utils.py", line 48, in get_file_handle
etl_1             |     fh = open(filename, full_mode)
etl_1             | PermissionError: [Errno 13] Permission denied: 'last_synced_block.txt'
```

**Comment by shinyfoil** [comment]
Ah, okay, so it's never actually worked correctly since we started using ETL and setting the block number by hand.

It makes sense though: the container is running as "iconetl" and the actions runner is the one creating the file, so that would explain why it's not letting you write to it.

Easiest solution is either chown it (which would require you to have the same user on the runner), or just chmod 777 (which is probably more straightforward).

@pranav925 , is this the standard action for these? We'll have to make that change everywhere if that's the case.

**Comment by pranav925** [comment]
The action is generic, used in icon-block. icon-transactions, icon-logs, and icon-addresses

**Comment by shinyfoil** [comment]
Cool, I'll check that the chmod works in blocks and then apply it all over

**Comment by shinyfoil** [comment]
Blocks, logs, transactions, and addresses have all been updated. Blocks built fine, so I skipped CI on the rest.
