### ISSUE TITLE
Test protobuf icon-etl version

### ISSUE THREAD

**Issue by pranav925** [geometry-labs/icon-blocks#13]

**Comment by pranav925** [comment]
Running into an error while building icon-etl:

```
Sending build context to Docker daemon  883.7kB
Step 1/16 : FROM python:3.6 as compile
3.6: Pulling from library/python
0bc3020d05f1: Already exists
a110e5871660: Already exists
83d3c0fa203a: Already exists
a8fd09c11b02: Already exists
14feb89c4a52: Already exists
7cb1b3b14e70: Pull complete
b35c6c2532e4: Pull complete
48fb5e50fe5f: Pull complete
0ceb42eae510: Pull complete
Digest: sha256:60f6954e7819a4d9380649bf7c1b95d7c6bf82fc4f625220ff9da3b4204c0698
Status: Downloaded newer image for python:3.6
 ---> 5fad76530472
Step 2/16 : MAINTAINER Richard Mah <richard@geometrylabs.io>
 ---> Running in 80bee8c0fd21
Removing intermediate container 80bee8c0fd21
 ---> a5b72bc05b6c
Step 3/16 : ENV PROJECT_DIR=icon-etl
 ---> Running in c8212192b29c
Removing intermediate container c8212192b29c
 ---> e26704e4c55e
Step 4/16 : WORKDIR /$PROJECT_DIR
 ---> Running in ac21b86aaea7
Removing intermediate container ac21b86aaea7
 ---> 0f779fd39318
Step 5/16 : COPY --chown=iconetl:iconetl . .
unable to convert uid/gid chown string to host mapping: can't find uid for user iconetl: no such user: iconetl
```

**Comment by shinyfoil** [comment]
Added a line to create the same user in the builder container. This is one of those weird "didn't error for me in buildx" things, but I know why it's not working.

Give it a try now.

**Comment by pranav925** [comment]
Thanks! it Fixed that error, but not it has this error:

```
Sending build context to Docker daemon  890.9kB
Step 1/17 : FROM python:3.6 as compile
 ---> 5fad76530472
Step 2/17 : MAINTAINER Richard Mah <richard@geometrylabs.io>
 ---> Using cache
 ---> a5b72bc05b6c
Step 3/17 : ENV PROJECT_DIR=icon-etl
 ---> Using cache
 ---> e26704e4c55e
Step 4/17 : WORKDIR /$PROJECT_DIR
 ---> Using cache
 ---> 0f779fd39318
Step 5/17 : RUN useradd -ms /bin/bash iconetl && mkdir /$PROJECT_DIR && chown -R iconetl:iconetl /$PROJECT_DIR
 ---> Running in fe66870ed9bc
mkdir: cannot create directory ‘/icon-etl’: File exists
The command '/bin/sh -c useradd -ms /bin/bash iconetl && mkdir /$PROJECT_DIR && chown -R iconetl:iconetl /$PROJECT_DIR' returned a non-zero code: 1
```

**Comment by shinyfoil** [comment]
Rearranged the order of the build and that should fix it. Give it a try now.

**Comment by pranav925** [comment]
The image builds and runs, but it is running into an error on runtime:

```
etl_1             | 2021-07-21 18:38:22,798 - root [INFO] - Nothing to sync. Sleeping for 1 seconds...
etl_1             | 2021-07-21 18:38:24,724 - root [INFO] - Current block 37277978, target block 100, last synced block 0, blocks to sync 100
etl_1             | 2021-07-21 18:38:24,724 - ProgressLogger [INFO] - Started work. Items to process: 100.
etl_1             | 2021-07-21 18:38:25,067 - ProgressLogger [INFO] - 100 items processed. Progress is 100%.
etl_1             | 2021-07-21 18:38:25,067 - ProgressLogger [INFO] - Finished work. Total items processed: 100. Took 0:00:00.343037.
etl_1             | 2021-07-21 18:38:25,067 - ProgressLogger [INFO] - Started work.
etl_1             | 2021-07-21 18:38:25,286 - ProgressLogger [INFO] - Finished work. Total items processed: 101. Took 0:00:00.218840.
etl_1             | 2021-07-21 18:38:25,288 - root [INFO] - Exporting with KafkaItemExporter
etl_1             | 2021-07-21 18:38:25,312 - root [ERROR] - An exception occurred while syncing block data.
etl_1             | Traceback (most recent call last):
etl_1             |   File "/usr/local/lib/python3.6/site-packages/blockchain_etl_common-1.3.0-py3.6.egg/blockchainetl_common/streaming/streamer.py", line 77, in _do_stream
etl_1             |     synced_blocks = self._sync_cycle()
etl_1             |   File "/usr/local/lib/python3.6/site-packages/blockchain_etl_common-1.3.0-py3.6.egg/blockchainetl_common/streaming/streamer.py", line 98, in _sync_cycle
etl_1             |     self.blockchain_streamer_adapter.export_all(self.last_synced_block + 1, target_block)
etl_1             |   File "/icon-etl/iconetl/streaming/icx_streamer_adapter.py", line 104, in export_all
etl_1             |     self.item_exporter.export_items(all_items)
etl_1             |   File "/icon-etl/iconetl/jobs/exporters/kafka_item_exporter.py", line 127, in export_items
etl_1             |     from_address=item["from"],
etl_1             | KeyError: 'from'
```

**Comment by shinyfoil** [comment]
Alrighty, transaction field names should be fixed up now. Give that a shot.

**Comment by pranav925** [comment]
Another field parsing error:
Might have to do with the `--to-hex-value` flag

```
etl_1             | 2021-07-21 21:23:16,665 - root [INFO] - Nothing to sync. Sleeping for 1 seconds...
etl_1             | 2021-07-21 21:23:17,874 - root [INFO] - Current block 37282707, target block 100, last synced block 0, blocks to sync 100
etl_1             | 2021-07-21 21:23:17,874 - ProgressLogger [INFO] - Started work. Items to process: 100.
etl_1             | 2021-07-21 21:23:18,170 - ProgressLogger [INFO] - 100 items processed. Progress is 100%.
etl_1             | 2021-07-21 21:23:18,171 - ProgressLogger [INFO] - Finished work. Total items processed: 100. Took 0:00:00.296754.
etl_1             | 2021-07-21 21:23:18,171 - ProgressLogger [INFO] - Started work.
etl_1             | 2021-07-21 21:23:18,610 - ProgressLogger [INFO] - Finished work. Total items processed: 101. Took 0:00:00.438816.
etl_1             | 2021-07-21 21:23:18,612 - root [INFO] - Exporting with KafkaItemExporter
etl_1             | 2021-07-21 21:23:18,640 - root [ERROR] - An exception occurred while syncing block data.
etl_1             | Traceback (most recent call last):
etl_1             |   File "/usr/local/lib/python3.6/site-packages/blockchain_etl_common-1.3.0-py3.6.egg/blockchainetl_common/streaming/streamer.py", line 77, in _do_stream
etl_1             |     synced_blocks = self._sync_cycle()
etl_1             |   File "/usr/local/lib/python3.6/site-packages/blockchain_etl_common-1.3.0-py3.6.egg/blockchainetl_common/streaming/streamer.py", line 98, in _sync_cycle
etl_1             |     self.blockchain_streamer_adapter.export_all(self.last_synced_block + 1, target_block)
etl_1             |   File "/icon-etl/iconetl/streaming/icx_streamer_adapter.py", line 104, in export_all
etl_1             |     self.item_exporter.export_items(all_items)
etl_1             |   File "/icon-etl/iconetl/jobs/exporters/kafka_item_exporter.py", line 152, in export_items
etl_1             |     item_timestamp=item["item_timestamp"],
etl_1             |   File "/usr/local/lib/python3.6/site-packages/protobuf-3.17.3-py3.6.egg/google/protobuf/internal/python_message.py", line 569, in init
etl_1             |     setattr(self, field_name, field_value)
etl_1             |   File "/usr/local/lib/python3.6/site-packages/protobuf-3.17.3-py3.6.egg/google/protobuf/internal/python_message.py", line 713, in field_setter
etl_1             |     new_value = type_checker.CheckValue(new_value)
etl_1             |   File "/usr/local/lib/python3.6/site-packages/protobuf-3.17.3-py3.6.egg/google/protobuf/internal/type_checkers.py", line 168, in CheckValue
etl_1             |     raise ValueError('Value out of range: %d' % proposed_value)
etl_1             | ValueError: Value out of range: 8004600000000000000000000
```
