### ISSUE TITLE
BUG: Sarama seg fault on multi-worker setup 

### ISSUE THREAD

**Issue by pranav925** [geometry-labs/icon-blocks#90]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x80fab0]
goroutine 538 [running[]:
github.com/geometry-labs/icon-blocks/kafka.(*ClaimConsumer).ConsumeClaim(0xc000273f20, 0x11e6c18, 0xc000378d80, 0x11e2658, 0xc00e5e97d0, 0xe, 0x4)
    /build/kafka/consumer.go:136 +0x170
gopkg.in/Shopify/sarama%2ev1.(*consumerGroupSession).consume(0xc000378d80, 0xc002fa55c0, 0xe, 0x4)
    /go/pkg/mod/gopkg.in/!shopify/sarama.v1@v1.20.1/consumer_group.go:594 +0x255
gopkg.in/Shopify/sarama%2ev1.newConsumerGroupSession.func2(0xc000378d80, 0xc002fa55c0, 0xe, 0xc000000004)
    /go/pkg/mod/gopkg.in/!shopify/sarama.v1@v1.20.1/consumer_group.go:523 +0x87
created by gopkg.in/Shopify/sarama%2ev1.newConsumerGroupSession
    /go/pkg/mod/gopkg.in/!shopify/sarama.v1@v1.20.1/consumer_group.go:515 +0x539
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x80fab0]
goroutine 541 [running[]:
github.com/geometry-labs/icon-blocks/kafka.(*ClaimConsumer).ConsumeClaim(0xc000273f20, 0x11e6c18, 0xc000378d80, 0x11e2658, 0xc00e5e9800, 0xe, 0x7)
    /build/kafka/consumer.go:136 +0x170
gopkg.in/Shopify/sarama%2ev1.(*consumerGroupSession).consume(0xc000378d80, 0xc002fa55c0, 0xe, 0x7)
    /go/pkg/mod/gopkg.in/!shopify/sarama.v1@v1.20.1/consumer_group.go:594 +0x255
gopkg.in/Shopify/sarama%2ev1.newConsumerGroupSession.func2(0xc000378d80, 0xc002fa55c0, 0xe, 0xc000000007)
    /go/pkg/mod/gopkg.in/!shopify/sarama.v1@v1.20.1/consumer_group.go:523 +0x87
created by gopkg.in/Shopify/sarama%2ev1.newConsumerGroupSession
    /go/pkg/mod/gopkg.in/!shopify/sarama.v1@v1.20.1/consumer_group.go:515 +0x539
```

**Comment by pranav925** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x8d1b70]
goroutine 890 [running[]:
github.com/geometry-labs/icon-logs/kafka.(*ClaimConsumer).ConsumeClaim(0xc00031a990, 0x1237e68, 0xc004f54f00, 0x1230c38, 0xc004f78810, 0xe, 0x0)
    /build/kafka/consumer.go:136 +0x170
github.com/Shopify/sarama.(*consumerGroupSession).consume(0xc004f54f00, 0xc004f66640, 0xe, 0x3633346200000000)
    /go/pkg/mod/github.com/!shopify/sarama@v1.29.1/consumer_group.go:690 +0x255
github.com/Shopify/sarama.newConsumerGroupSession.func2(0xc004f54f00, 0xc004f66640, 0xe, 0xc000000000)
    /go/pkg/mod/github.com/!shopify/sarama@v1.29.1/consumer_group.go:615 +0x87
created by github.com/Shopify/sarama.newConsumerGroupSession
    /go/pkg/mod/github.com/!shopify/sarama@v1.29.1/consumer_group.go:607 +0x539
```
